"""
ServiceApplication = one citizen's application for one service.

`reference_no` is generated by our code right after the row gets its
database id (see app/api/applications.py) — it's what a citizen would
quote if they called up asking "what's happening with my application?"

`payload` is JSONB, same idea as Service.requirements — different
services need different application fields (some need a meter number,
some need a business registration number, etc), so we store whatever
the citizen submitted as flexible JSON rather than fixed columns.

`status` starts as "submitted" and can only move forward through
specific steps — see app/services/workflow.py for the actual rules.
"""

from sqlalchemy import String, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base


class ServiceApplication(Base):
    __tablename__ = "service_applications"

    id: Mapped[int] = mapped_column(primary_key=True)
    citizen_id: Mapped[int] = mapped_column(ForeignKey("citizens.id"), nullable=False)
    service_id: Mapped[int] = mapped_column(ForeignKey("services.id"), nullable=False)
    reference_no: Mapped[str] = mapped_column(String(30), unique=True, nullable=False, index=True)
    payload: Mapped[dict] = mapped_column(JSONB, default=dict)
    status: Mapped[str] = mapped_column(String(20), default="submitted", nullable=False)

    citizen: Mapped["Citizen"] = relationship()
    service: Mapped["Service"] = relationship()
